import { StyleSheet, Platform } from 'react-native';
import { RADIUS, SHADOWS } from './theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F5F4',
  },
  header: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
    backgroundColor: '#FFFFFF',
  },
  headerText: {
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'sans-serif',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D1D15',
    letterSpacing: 0.5,
  },
  headerDot: {
    color: '#6F405F',
    fontSize: 22,
    marginLeft: 3,
    fontWeight: 'bold',
  },
  tabBar: {
    height: 60,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#E1DCDB',
    backgroundColor: '#FFFFFF',
    paddingBottom: Platform.OS === 'ios' ? 10 : 0,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonText: {
    fontSize: 12,
    color: '#8C8385',
    fontWeight: '600',
  },
  tabButtonTextActive: {
    color: '#6F405F',
    fontWeight: 'bold',
  },

  // Auth Screen styles
  authContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#F8F5F4',
  },
  authCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    padding: 24,
    ...SHADOWS.medium,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E1DCDB',
  },
  authLogoCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(111, 64, 95, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  authLogoText: {
    fontSize: 28,
  },
  brandTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginBottom: 6,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'sans-serif',
  },
  brandSubtitle: {
    fontSize: 12,
    color: '#8C8385',
    marginBottom: 24,
    textAlign: 'center',
  },
  authHeader: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#6F405F',
    marginBottom: 16,
    alignSelf: 'flex-start',
    letterSpacing: 0.2,
  },
  input: {
    width: '100%',
    height: 48,
    borderWidth: 1,
    borderColor: '#CEC7C5',
    borderRadius: RADIUS.sm,
    paddingHorizontal: 12,
    marginBottom: 14,
    fontSize: 14,
    color: '#2D1D15',
    backgroundColor: '#FAF8F8',
  },
  primaryButton: {
    width: '100%',
    height: 48,
    backgroundColor: '#6F405F',
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  switchAuthButton: {
    marginTop: 18,
  },
  switchAuthText: {
    color: '#8C8385',
    fontSize: 13,
  },
  errorBanner: {
    width: '100%',
    backgroundColor: 'rgba(196, 111, 118, 0.12)',
    padding: 10,
    borderRadius: RADIUS.sm,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(196, 111, 118, 0.3)',
  },
  errorText: {
    color: '#C46F76',
    fontSize: 13,
    textAlign: 'center',
  },

  // Common styles
  avatar: {
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOWS.subtle,
  },
  avatarText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },

  // Feed Screen styles
  feedContainer: {
    flex: 1,
  },
  topicsScrollContainer: {
    height: 52,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
  },
  topicsScroll: {
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  topicChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: RADIUS.pill,
    backgroundColor: '#FAF8F8',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#CEC7C5',
  },
  topicChipText: {
    fontSize: 12,
    color: '#8C8385',
  },
  feedScroll: {
    padding: 12,
  },
  postCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    padding: 16,
    marginBottom: 12,
    ...SHADOWS.soft,
    borderWidth: 1,
    borderColor: '#E1DCDB',
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  postHeaderInfo: {
    marginLeft: 10,
    flex: 1,
  },
  postUsername: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#2D1D15',
  },
  postMeta: {
    fontSize: 11,
    color: '#8C8385',
    marginTop: 1,
  },
  topicBadgePill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.pill,
    borderWidth: 1.2,
  },
  topicBadgeText: {
    fontSize: 10.5,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  postTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginBottom: 6,
    letterSpacing: 0.1,
  },
  postContent: {
    fontSize: 14,
    color: '#6b6375',
    lineHeight: 20,
    marginBottom: 14,
  },
  reactionsDisplayRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  reactionBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: '#FAF8F8',
    borderWidth: 1,
    borderColor: '#E1DCDB',
  },
  reactionBadgeActive: {
    backgroundColor: '#6F405F',
    borderColor: '#6F405F',
  },
  reactionBadgeText: {
    fontSize: 11,
    color: '#8C8385',
  },
  postActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#F8F5F4',
    paddingTop: 12,
  },
  emojiPickerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  emojiPickerButton: {
    padding: 3,
  },
  emojiPickerText: {
    fontSize: 18,
  },
  actionButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  commentActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.pill,
    backgroundColor: '#FAF8F8',
    borderWidth: 1,
    borderColor: '#E1DCDB',
  },
  commentActionButtonText: {
    fontSize: 12,
    color: '#8C8385',
    fontWeight: '600',
  },
  chatActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(111, 64, 95, 0.08)',
    borderRadius: RADIUS.pill,
    borderWidth: 1,
    borderColor: 'rgba(111, 64, 95, 0.2)',
  },
  chatActionButtonText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#6F405F',
  },
  flagActionButton: {
    padding: 4,
  },
  flagActionButtonText: {
    fontSize: 13,
  },

  // Create Screen styles
  createContainer: {
    flex: 1,
  },
  screenTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6F405F',
    marginBottom: 6,
    marginTop: 8,
  },
  pickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  pickerChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.pill,
    backgroundColor: '#FAF8F8',
    borderWidth: 1,
    borderColor: '#CEC7C5',
  },
  pickerChipActive: {
    backgroundColor: '#6F405F',
    borderColor: '#6F405F',
  },
  pickerChipText: {
    fontSize: 12,
    color: '#8C8385',
  },
  pickerChipTextActive: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  publishButton: {
    backgroundColor: '#6F405F',
    height: 48,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
    marginBottom: 30,
  },
  publishButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },

  // Comment Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(45, 29, 21, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    height: '80%',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: RADIUS.lg,
    borderTopRightRadius: RADIUS.lg,
    overflow: 'hidden',
  },
  modalHeader: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#2D1D15',
  },
  modalCloseButton: {
    padding: 6,
  },
  modalCloseText: {
    fontSize: 18,
    color: '#8C8385',
  },
  modalPostBrief: {
    backgroundColor: '#FAF8F8',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
  },
  modalPostUser: {
    fontWeight: 'bold',
    fontSize: 12,
    color: '#6F405F',
    marginBottom: 2,
  },
  modalPostText: {
    fontSize: 13,
    color: '#8C8385',
  },
  commentCard: {
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F8F5F4',
    paddingBottom: 10,
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  commentUser: {
    fontWeight: 'bold',
    fontSize: 12,
    color: '#2D1D15',
    marginLeft: 8,
  },
  commentContent: {
    fontSize: 13,
    color: '#6b6375',
    marginLeft: 36,
  },
  commentComposerBar: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E1DCDB',
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    marginBottom: Platform.OS === 'ios' ? 20 : 0,
  },
  commentComposerInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: '#CEC7C5',
    borderRadius: RADIUS.pill,
    paddingHorizontal: 16,
    fontSize: 13,
    color: '#2D1D15',
    backgroundColor: '#FAF8F8',
  },
  commentSendButton: {
    marginLeft: 10,
    paddingHorizontal: 14,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentSendText: {
    color: '#6F405F',
    fontWeight: 'bold',
    fontSize: 14,
  },

  // Chat/Conversation list styles
  chatContainer: {
    flex: 1,
    padding: 16,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
  },
  emptyText: {
    color: '#9F9794',
    textAlign: 'center',
    fontSize: 14,
  },
  convoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
  },
  convoInfo: {
    flex: 1,
    marginLeft: 12,
  },
  convoTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  convoName: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#2D1D15',
  },
  unreadBadge: {
    backgroundColor: '#6F405F',
    borderRadius: RADIUS.pill,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  unreadBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  convoLastMsg: {
    fontSize: 12,
    color: '#8C8385',
    marginTop: 3,
  },

  // Chat Detail Thread styles
  chatDetailContainer: {
    flex: 1,
    backgroundColor: '#FAF8F8',
  },
  chatDetailHeader: {
    height: 52,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  backButton: {
    paddingRight: 10,
  },
  backButtonText: {
    fontSize: 13,
    color: '#6F405F',
    fontWeight: 'bold',
  },
  chatHeaderName: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#2D1D15',
    marginLeft: 8,
  },
  messagesList: {
    padding: 16,
    paddingBottom: 24,
  },
  messageBubbleContainer: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
  },
  msgMeContainer: {
    justifyContent: 'flex-end',
  },
  msgPartnerContainer: {
    justifyContent: 'flex-start',
  },
  messageBubble: {
    maxWidth: '75%',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
  },
  msgMeBubble: {
    backgroundColor: '#6F405F',
    borderBottomRightRadius: 2,
  },
  msgPartnerBubble: {
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 2,
    borderWidth: 1,
    borderColor: '#E1DCDB',
  },
  messageText: {
    fontSize: 13,
    lineHeight: 18,
  },
  msgMeText: {
    color: '#FFFFFF',
  },
  msgPartnerText: {
    color: '#2D1D15',
  },
  chatComposerRow: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E1DCDB',
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    marginBottom: Platform.OS === 'ios' ? 20 : 0,
  },
  chatComposerInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: '#CEC7C5',
    borderRadius: RADIUS.pill,
    paddingHorizontal: 16,
    fontSize: 13,
    color: '#2D1D15',
    backgroundColor: '#FAF8F8',
  },
  chatSendButton: {
    marginLeft: 10,
    backgroundColor: '#6F405F',
    paddingHorizontal: 14,
    height: 38,
    borderRadius: RADIUS.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSendButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 12,
  },

  // Profile Screen styles
  profileContainer: {
    flex: 1,
  },
  profileHero: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 24,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
  },
  profileName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginTop: 10,
  },
  profileUsername: {
    fontSize: 13,
    color: '#8C8385',
    marginTop: 2,
  },
  avatarColorSelector: {
    marginTop: 16,
    alignItems: 'center',
  },
  selectorLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#8C8385',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  colorPaletteRow: {
    flexDirection: 'row',
    gap: 10,
  },
  paletteCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CEC7C5',
  },
  paletteCircleActive: {
    borderWidth: 3,
    borderColor: '#2D1D15',
  },
  statsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    margin: 16,
    borderRadius: RADIUS.md,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: '#E1DCDB',
    ...SHADOWS.subtle,
  },
  statColumn: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#6F405F',
  },
  statLabel: {
    fontSize: 11,
    color: '#8C8385',
    marginTop: 2,
  },
  bioCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: RADIUS.md,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E1DCDB',
    ...SHADOWS.subtle,
  },
  bioHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  bioTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#6F405F',
  },
  bioEditButtonText: {
    fontSize: 12,
    color: '#8C8385',
  },
  bioText: {
    fontSize: 13,
    color: '#6b6375',
    lineHeight: 18,
  },
  bioEditForm: {
    width: '100%',
  },
  bioTextInput: {
    borderWidth: 1,
    borderColor: '#CEC7C5',
    borderRadius: RADIUS.sm,
    padding: 10,
    fontSize: 13,
    color: '#2D1D15',
    backgroundColor: '#FAF8F8',
    height: 60,
    textAlignVertical: 'top',
    marginBottom: 10,
  },
  bioSaveButton: {
    backgroundColor: '#6F405F',
    height: 36,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bioSaveText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 12,
  },
  adminToggleBtn: {
    marginTop: 12,
    backgroundColor: '#8C8385',
    height: 40,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminToggleBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 'bold',
  },
  logoutButton: {
    marginHorizontal: 16,
    marginBottom: 30,
    height: 48,
    borderRadius: RADIUS.sm,
    backgroundColor: 'rgba(196, 111, 118, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(196, 111, 118, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutButtonText: {
    color: '#C46F76',
    fontWeight: 'bold',
    fontSize: 14,
  },

  // Admin Portal styling
  adminSubTabRow: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E1DCDB',
  },
  adminSubTabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  adminSubTabButtonActive: {
    borderBottomColor: '#6F405F',
  },
  adminSubTabButtonText: {
    fontSize: 13,
    color: '#8C8385',
    fontWeight: '500',
  },
  adminSectionHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginTop: 8,
  },
  adminSectionSub: {
    fontSize: 12,
    color: '#8C8385',
    marginBottom: 16,
  },
  metricGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  metricCard: {
    flex: 1,
    borderRadius: RADIUS.md,
    padding: 16,
    borderWidth: 1,
    ...SHADOWS.subtle,
  },
  metricEmoji: {
    fontSize: 22,
    marginBottom: 8,
  },
  metricNumber: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginBottom: 2,
  },
  metricTitle: {
    fontSize: 12,
    color: '#8C8385',
    fontWeight: '600',
  },
  systemLogsCard: {
    backgroundColor: '#2D1D15',
    borderRadius: RADIUS.md,
    padding: 16,
    marginTop: 18,
    ...SHADOWS.subtle,
  },
  systemLogsTitle: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  logRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  logBullet: {
    color: '#C46F76',
    fontWeight: 'bold',
    marginRight: 8,
  },
  logText: {
    color: '#FAF8F8',
    fontSize: 12,
    flex: 1,
    lineHeight: 16,
  },

  // Reports list styling
  reportCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E1DCDB',
    ...SHADOWS.soft,
  },
  reportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  riskBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  riskBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  reportTime: {
    fontSize: 11,
    color: '#8C8385',
  },
  reportQuoteBlock: {
    backgroundColor: '#FAF8F8',
    borderLeftWidth: 3,
    borderLeftColor: '#6F405F',
    padding: 10,
    borderRadius: 4,
    marginBottom: 12,
  },
  reportQuoteUser: {
    fontSize: 11.5,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginBottom: 3,
  },
  reportQuoteText: {
    fontSize: 12.5,
    color: '#6b6375',
    fontStyle: 'italic',
    lineHeight: 18,
  },
  reportNotesText: {
    fontSize: 12,
    color: '#8C8385',
    marginBottom: 14,
    lineHeight: 16,
  },
  resolveActionBtn: {
    backgroundColor: '#6F405F',
    height: 38,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resolveActionBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 12.5,
  },
  resolutionBadge: {
    padding: 8,
    backgroundColor: 'rgba(63, 119, 114, 0.08)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(63, 119, 114, 0.3)',
  },
  resolutionBadgeText: {
    fontSize: 11,
    color: '#3F7772',
    fontWeight: '600',
    textAlign: 'center',
  },

  // Modals & Centered cards
  centerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(45, 29, 21, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  reportModalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    padding: 20,
    ...SHADOWS.medium,
    borderWidth: 1,
    borderColor: '#E1DCDB',
  },
  reportModalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginBottom: 6,
  },
  reportModalSubtitle: {
    fontSize: 12.5,
    color: '#8C8385',
    marginBottom: 14,
    lineHeight: 16,
  },
  reportSelectorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  reportReasonChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.pill,
    backgroundColor: '#FAF8F8',
    borderWidth: 1,
    borderColor: '#CEC7C5',
  },
  reportReasonChipActive: {
    backgroundColor: '#6F405F',
    borderColor: '#6F405F',
  },
  reportReasonText: {
    fontSize: 11.5,
    color: '#8C8385',
  },
  reportActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 16,
  },
  reportCancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  reportCancelText: {
    color: '#8C8385',
    fontWeight: 'bold',
    fontSize: 13,
  },
  reportSubmitButton: {
    backgroundColor: '#C46F76',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: RADIUS.sm,
  },
  reportSubmitText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },

  // Moderation modal specifics
  moderationCardQuote: {
    backgroundColor: '#FAF8F8',
    padding: 10,
    borderRadius: 6,
    borderLeftWidth: 3,
    borderLeftColor: '#CEC7C5',
    marginBottom: 10,
  },
  moderationCardQuoteText: {
    fontSize: 12,
    fontStyle: 'italic',
    color: '#8C8385',
  },
  moderationActionColumn: {
    flexDirection: 'column',
    gap: 10,
    marginTop: 14,
  },
  moderationActionBtn: {
    height: 42,
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moderationActionBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  moderationCancelBtn: {
    marginTop: 14,
    alignItems: 'center',
    paddingVertical: 8,
  },
  moderationCancelBtnText: {
    color: '#8C8385',
    fontWeight: 'bold',
    fontSize: 13,
  },
  infoActionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
  },
  infoActionBtn: {
    flex: 1,
    height: 40,
    backgroundColor: '#FAF8F8',
    borderWidth: 1,
    borderColor: '#CEC7C5',
    borderRadius: RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoActionText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#6F405F',
  },
  policyHeading: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginTop: 14,
    marginBottom: 6,
  },
  policyBody: {
    fontSize: 13,
    color: '#8C8385',
    lineHeight: 18,
    marginBottom: 12,
  },
  policyBullet: {
    fontSize: 13,
    color: '#8C8385',
    lineHeight: 18,
    marginBottom: 8,
    paddingLeft: 8,
  },
  headerLoginShortcut: {
    position: 'absolute',
    right: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: RADIUS.pill,
    backgroundColor: 'rgba(111, 64, 95, 0.1)',
  },
  headerLoginShortcutText: {
    color: '#6F405F',
    fontWeight: 'bold',
    fontSize: 12.5,
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    borderWidth: 1,
    borderColor: '#CEC7C5',
    borderRadius: RADIUS.sm,
    backgroundColor: '#FAF8F8',
    marginBottom: 14,
    paddingRight: 10,
  },
  passwordEyeBtn: {
    padding: 8,
  },
  passwordEyeText: {
    fontSize: 16,
  },
  privacyBadgesRow: {
    flexDirection: 'row',
    gap: 8,
    marginVertical: 10,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  privacyBadge: {
    backgroundColor: 'rgba(45, 29, 21, 0.05)',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: RADIUS.pill,
  },
  privacyBadgeText: {
    fontSize: 11,
    color: '#8C8385',
    fontWeight: '600',
  },
  checkboxesContainer: {
    width: '100%',
    marginVertical: 12,
    gap: 10,
  },
  checkRowContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    width: '100%',
  },
  checkboxBox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#8C8385',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginTop: 1,
  },
  checkboxBoxChecked: {
    backgroundColor: '#6F405F',
    borderColor: '#6F405F',
  },
  checkboxTick: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  checkRowText: {
    fontSize: 12,
    color: '#2D1D15',
    flex: 1,
    lineHeight: 18,
  },
  otpNoticeRow: {
    backgroundColor: 'rgba(111, 64, 95, 0.06)',
    padding: 10,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: 'rgba(111, 64, 95, 0.15)',
    marginBottom: 10,
  },
  otpNoticeText: {
    fontSize: 12,
    color: '#6F405F',
  },
  otpActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  otpResendBtn: {
    paddingVertical: 8,
  },
  otpResendText: {
    fontSize: 12.5,
    fontWeight: 'bold',
    color: '#6F405F',
    textDecorationLine: 'underline',
  },
  otpVerifyBtn: {
    backgroundColor: '#6F405F',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: RADIUS.sm,
  },
  otpVerifyText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 'bold',
  },
  authBackBtn: {
    alignSelf: 'flex-start',
    marginBottom: 14,
    paddingVertical: 4,
  },
  authBackBtnText: {
    fontSize: 12.5,
    color: '#8C8385',
    fontWeight: '600',
  },
  landingHeroBlock: {
    padding: 24,
    backgroundColor: '#0B0A16',
    alignItems: 'center',
    textAlign: 'center',
  },
  badgeBanner: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: RADIUS.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    marginBottom: 16,
  },
  badgeBannerText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '600',
  },
  landingHeroHeadline: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 40,
    marginBottom: 16,
  },
  landingHeroSubText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  landingHeroCtaRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  landingHeroCtaBtnPrimary: {
    backgroundColor: '#D89C7A',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: RADIUS.sm,
  },
  landingHeroCtaTextPrimary: {
    color: '#0B0A16',
    fontWeight: 'bold',
    fontSize: 14,
  },
  landingHeroCtaBtnSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: RADIUS.sm,
  },
  landingHeroCtaTextSecondary: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  trustBadgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 16,
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.12)',
    paddingTop: 16,
    width: '100%',
  },
  trustBadgeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  trustBadgeIcon: {
    fontSize: 14,
  },
  trustBadgeLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  landingSection: {
    padding: 24,
    backgroundColor: '#F8F5F4',
  },
  landingSectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D1D15',
    textAlign: 'center',
  },
  landingTitleDivider: {
    width: 32,
    height: 3,
    backgroundColor: '#D89C7A',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  featureCardItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E1DCDB',
    alignItems: 'center',
    textAlign: 'center',
    marginBottom: 16,
    ...SHADOWS.subtle,
  },
  featureCardIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#F8F5F4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  featureCardHeader: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#6F405F',
    marginBottom: 6,
  },
  featureCardBody: {
    fontSize: 13,
    color: '#8C8385',
    textAlign: 'center',
    lineHeight: 18,
  },
  howItWorksRow: {
    flexDirection: 'row',
    marginBottom: 20,
    gap: 16,
  },
  howItWorksNumberBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(111, 64, 95, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  howItWorksNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#6F405F',
  },
  howItWorksContent: {
    flex: 1,
  },
  howItWorksTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#2D1D15',
    marginBottom: 4,
  },
  howItWorksBody: {
    fontSize: 13,
    color: '#8C8385',
    lineHeight: 18,
  },
  safetyBulletBlock: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: '#E1DCDB',
  },
  safetyBulletIcon: {
    fontSize: 18,
    marginTop: 1,
  },
  safetyBulletText: {
    fontSize: 13,
    color: '#8C8385',
    flex: 1,
    lineHeight: 18,
  },
  landingFooterNav: {
    backgroundColor: '#2D1D15',
    padding: 32,
    alignItems: 'center',
  },
  footerBrandTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#F8F5F4',
    marginBottom: 6,
  },
  footerBrandDesc: {
    fontSize: 12.5,
    color: '#8C8385',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 18,
  },
  footerLinksGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(248, 245, 244, 0.1)',
    paddingBottom: 20,
    width: '100%',
  },
  footerNavLink: {
    paddingVertical: 4,
  },
  footerNavLinkText: {
    fontSize: 13,
    color: '#FAF8F8',
    fontWeight: '600',
  },
  footerCopyright: {
    fontSize: 11,
    color: '#8C8385',
  },
});

